import { Box, Button, Text, VStack } from "@chakra-ui/react";
import { FC, useEffect } from "react";
import {
  Formik,
  FormikHelpers,
  FormikProps,
  Form,
  Field,
  FieldProps,
} from "formik";
import { InputWithLabel } from "../UI";
import { useRouter } from "next/router";

export type FormValuesType = {
  id?: number;
  subId?: number;
  login?: string;
  password?: string;
  isLogged?: boolean;
  balance?: number;
  type?: string;
};

export const Auth: FC = () => {
  const { replace } = useRouter();
  useEffect(() => {
    if (!localStorage.getItem("secret")) {
      localStorage.setItem(
        "secret",
        JSON.stringify([
          {
            id: 0,
            login: "kornev",
            password: "msk9909512",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 1,
            login: "frein",
            password: "mso8112872",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 2,
            login: "radchuk",
            password: "tve6845851",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 3,
            login: "rogacheva",
            password: "kiy7397948",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 4,
            login: "zaparin",
            password: "kbv2803545",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 5,
            login: "kondakova",
            password: "trv6318591",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 6,
            login: "vasilieva",
            password: "olt3526478",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 7,
            login: "loboda",
            password: "sbk7848764",
            isLogged: false,
            balance: 500,
            type: "referrer",
          },
          {
            id: 0,
            subId: 0,
            login: "sbi69andreMO",
            password: "rst623728",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 1,
            subId: 0,
            login: "sbi69vesyeMO",
            password: "rst784299",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 2,
            subId: 0,
            login: "sbi69vyshnGO",
            password: "rst742972",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 3,
            subId: 0,
            login: "sbi69kimrsGO",
            password: "rst824849",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 4,
            subId: 0,
            login: "sbi69rzhevGO",
            password: "rst724974",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 5,
            subId: 0,
            login: "sbi69tverGO",
            password: "rst316386",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 6,
            subId: 0,
            login: "sbi69torzhGO",
            password: "rst935972",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 7,
            subId: 0,
            login: "sbi69zapadMO",
            password: "rst648486",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 8,
            subId: 0,
            login: "sbi69ozernGO",
            password: "rst622588",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 9,
            subId: 0,
            login: "sbi69solnecGO",
            password: "rst247792",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 10,
            subId: 0,
            login: "sbi69kashiGO",
            password: "rst084579",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 11,
            subId: 0,
            login: "sbi69krasnMO",
            password: "rst657392",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 12,
            subId: 0,
            login: "sbi69lesnoMO",
            password: "rst297947",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 13,
            subId: 0,
            login: "sbi69nelidGO",
            password: "rst975874",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 14,
            subId: 0,
            login: "sbi69oleniMO",
            password: "rst264862",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 15,
            subId: 0,
            login: "sbi69ostasGO",
            password: "rst083978",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 16,
            subId: 0,
            login: "sbi69penovMO",
            password: "rst136316",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 17,
            subId: 0,
            login: "sbi69sandoMO",
            password: "rst527572",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 18,
            subId: 0,
            login: "sbi69selizhMO",
            password: "rst826431",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 19,
            subId: 0,
            login: "sbi69udomeGO",
            password: "rst248826",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 20,
            subId: 0,
            login: "sbi69bezheMR",
            password: "rst974758",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 21,
            subId: 0,
            login: "sbi69belskMR",
            password: "rst347032",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 22,
            subId: 0,
            login: "sbi69bologMR",
            password: "rst932479",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 23,
            subId: 0,
            login: "sbi69zharkMR",
            password: "rst093250",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 24,
            subId: 0,
            login: "sbi69zubcoMR",
            password: "rst274979",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 25,
            subId: 0,
            login: "sbi69kalinMR",
            password: "rst264842",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 26,
            subId: 0,
            login: "sbi69kalyaMR",
            password: "rst982497",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 27,
            subId: 0,
            login: "sbi69kesovMR",
            password: "rst684268",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 28,
            subId: 0,
            login: "sbi69kimrsMR",
            password: "rst827472",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 29,
            subId: 0,
            login: "sbi69konakMR",
            password: "rst297407",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 30,
            subId: 0,
            login: "sbi69kuvshMR",
            password: "rst624685",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 31,
            subId: 0,
            login: "sbi69lihosMO",
            password: "rst082492",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 32,
            subId: 0,
            login: "sbi69maksaMR",
            password: "rst286484",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 33,
            subId: 0,
            login: "sbi69molokMO",
            password: "rst286486",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 34,
            subId: 0,
            login: "sbi69ramesMO",
            password: "rst274927",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 35,
            subId: 0,
            login: "sbi69rzhevMR",
            password: "rst824862",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 36,
            subId: 0,
            login: "sbi69sonkoMR",
            password: "rst286482",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 37,
            subId: 0,
            login: "sbi69spiroMO",
            password: "rst024892",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 38,
            subId: 0,
            login: "sbi69stariMR",
            password: "rst827462",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 39,
            subId: 0,
            login: "sbi69torzhMR",
            password: "rst824828",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 40,
            subId: 0,
            login: "sbi69toropMR",
            password: "rst824864",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 41,
            subId: 0,
            login: "sbi69firovMR",
            password: "rst727554",
            isLogged: false,
            balance: 500,
            type: "referral",
          },




          {
            id: 0,
            subId: 1,
            login: "sbi40kaluzGO",
            password: "rst648648",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 1,
            subId: 1,
            login: "sbi40obninGO",
            password: "rst724779",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 2,
            subId: 1,
            login: "sbi40babynMR",
            password: "rst747593",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 3,
            subId: 1,
            login: "sbi40bagryMR",
            password: "rst836843",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 4,
            subId: 1,
            login: "sbi40borovMR",
            password: "rst982480",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 5,
            subId: 1,
            login: "sbi40dzerzMR",
            password: "rst284284",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 6,
            subId: 1,
            login: "sbi40duminMR",
            password: "rst724729",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 7,
            subId: 1,
            login: "sbi40zhizdMR",
            password: "rst274294",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 8,
            subId: 1,
            login: "sbi40zhukoMR",
            password: "rst573648",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 9,
            subId: 1,
            login: "sbi40iznosMR",
            password: "rst589391",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 10,
            subId: 1,
            login: "sbi40kirovMR",
            password: "rst397539",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 11,
            subId: 1,
            login: "sbi40kozelMR",
            password: "rst083593",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 12,
            subId: 1,
            login: "sbi40kuybyMR",
            password: "rst536763",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 13,
            subId: 1,
            login: "sbi40lyudiMR",
            password: "rst837485",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 14,
            subId: 1,
            login: "sbi40maloyMR",
            password: "rst935772",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 15,
            subId: 1,
            login: "sbi40medynMR",
            password: "rst935973",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 16,
            subId: 1,
            login: "sbi40meshcMR",
            password: "rst653622",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 17,
            subId: 1,
            login: "sbi40mosalMR",
            password: "rst045823",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 18,
            subId: 1,
            login: "sbi40peremMR",
            password: "rst354282",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 19,
            subId: 1,
            login: "sbi40spasdMR",
            password: "rst265421",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 20,
            subId: 1,
            login: "sbi40suhinMR",
            password: "rst836428",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 21,
            subId: 1,
            login: "sbi40tarusMR",
            password: "rst373292",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 22,
            subId: 0,
            login: "sbi40ulianMR",
            password: "rst276480",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 23,
            subId: 1,
            login: "sbi40ferzinMR",
            password: "rst037256",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 24,
            subId: 1,
            login: "sbi40hvastMR",
            password: "rst927426",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 25,
            subId: 1,
            login: "sbi40yuhnoMR",
            password: "rst236520",
            isLogged: false,
            balance: 500,
            type: "referral",
          },

          {
            id: 0,
            subId: 2,
            login: "sbi76peresGO",
            password: "rst871247",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 1,
            subId: 2,
            login: "sbi76rybinGO",
            password: "rst126491",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 2,
            subId: 2,
            login: "sbi76yarosGO",
            password: "rst727473",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 3,
            subId: 2,
            login: "sbi76bolsheMR",
            password: "rst674938",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 4,
            subId: 2,
            login: "sbi76borisMR",
            password: "rst242941",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 5,
            subId: 2,
            login: "sbi76breytoMR",
            password: "rst924874",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 6,
            subId: 2,
            login: "sbi76gavriMR",
            password: "rst982372",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 7,
            subId: 2,
            login: "sbi76danilMR",
            password: "rst729471",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 8,
            subId: 2,
            login: "sbi76lubimMR",
            password: "rst923736",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 9,
            subId: 2,
            login: "sbi76myshkMR",
            password: "rst826481",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 10,
            subId: 2,
            login: "sbi76nekouMR",
            password: "rst264920",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 11,
            subId: 2,
            login: "sbi76nekrasMR",
            password: "rst027822",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 12,
            subId: 2,
            login: "sbi76pervoMR",
            password: "rst892400",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 13,
            subId: 2,
            login: "sbi76peresMR",
            password: "rst726488",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 14,
            subId: 2,
            login: "sbi76posheMR",
            password: "rst824914",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 15,
            subId: 2,
            login: "sbi76rostovMR",
            password: "rst286428",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 16,
            subId: 2,
            login: "sbi76rybinMR",
            password: "rst824154",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 17,
            subId: 2,
            login: "sbi76tutaeMR",
            password: "rst928464",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 18,
            subId: 2,
            login: "sbi76uglichMR",
            password: "rst722451",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 19,
            subId: 2,
            login: "sbi76yarosMR",
            password: "rst724750",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          
          


          {
            id: 0,
            subId: 3,
            login: "sbi46zheleGO",
            password: "rst004515",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 1,
            subId: 3,
            login: "sbi46kurskGO",
            password: "rst124724",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 2,
            subId: 3,
            login: "sbi46kurchGO",
            password: "rst821646",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 3,
            subId: 3,
            login: "sbi46lgovsGO",
            password: "rst921649",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 4,
            subId: 3,
            login: "sbi46shigroGO",
            password: "rst898172",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 5,
            subId: 3,
            login: "sbi46belovMR",
            password: "rst619249",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 6,
            subId: 3,
            login: "sbi46bolshMR",
            password: "rst712414",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 7,
            subId: 3,
            login: "sbi46glushMR",
            password: "rst174819",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 8,
            subId: 3,
            login: "sbi46gorsheMR",
            password: "rst261714",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 9,
            subId: 3,
            login: "sbi46dmitrMR",
            password: "rst787142",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 10,
            subId: 3,
            login: "sbi46zhelezMR",
            password: "rst912740",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 11,
            subId: 3,
            login: "sbi46zolotMR",
            password: "rst815450",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 12,
            subId: 3,
            login: "sbi46kastorMR",
            password: "rst214949",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 13,
            subId: 3,
            login: "sbi46konysMR",
            password: "rst745312",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 14,
            subId: 3,
            login: "sbi46korenMR",
            password: "rst987524",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 15,
            subId: 3,
            login: "sbi46kurskMR",
            password: "rst986896",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 16,
            subId: 3,
            login: "sbi46kurchaMR",
            password: "rst849652",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 17,
            subId: 3,
            login: "sbi46lgovsMR",
            password: "rst029174",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 18,
            subId: 3,
            login: "sbi46mantuMR",
            password: "rst862474",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 19,
            subId: 3,
            login: "sbi46medveMR",
            password: "rst217401",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 20,
            subId: 3,
            login: "sbi46oboyaMR",
            password: "rst281621",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 21,
            subId: 3,
            login: "sbi46oktyaMR",
            password: "rst912462",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 22,
            subId: 3,
            login: "sbi46ponyrMR",
            password: "rst012565",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 23,
            subId: 3,
            login: "sbi46pristMR",
            password: "rst982817",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 24,
            subId: 3,
            login: "sbi46rylovMR",
            password: "rst217481",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 25,
            subId: 3,
            login: "sbi46sovetMR",
            password: "rst924919",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 26,
            subId: 3,
            login: "sbi46solncMR",
            password: "rst141001",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 27,
            subId: 3,
            login: "sbi46sudjaMR",
            password: "rst124911",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 28,
            subId: 3,
            login: "sbi46timskMR",
            password: "rst217491",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 29,
            subId: 3,
            login: "sbi46fatezMR",
            password: "rst987149",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 30,
            subId: 3,
            login: "sbi46homutMR",
            password: "rst917416",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 31,
            subId: 3,
            login: "sbi46cheremMR",
            password: "rst012749",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 32,
            subId: 3,
            login: "sbi46shigrMR",
            password: "rst428491",
            isLogged: false,
            balance: 500,
            type: "referral",
          },






          {
            id: 0,
            subId: 4,
            login: "sbi57livnoGO",
            password: "rst620848",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 1,
            subId: 4,
            login: "sbi57mcensGO",
            password: "rst275481",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 2,
            subId: 4,
            login: "sbi57orlovGO",
            password: "rst021748",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 3,
            subId: 4,
            login: "sbi57bolhoMR",
            password: "rst278541",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 4,
            subId: 4,
            login: "sbi57verhoMR",
            password: "rst901649",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 5,
            subId: 4,
            login: "sbi57glazuMR",
            password: "rst812401",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 6,
            subId: 4,
            login: "sbi57dmitrMR",
            password: "rst018244",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 7,
            subId: 4,
            login: "sbi57dolzhMR",
            password: "rst092947",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 8,
            subId: 4,
            login: "sbi57zalegMR",
            password: "rst921401",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 9,
            subId: 4,
            login: "sbi57znamyaMR",
            password: "rst912456",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 10,
            subId: 4,
            login: "sbi57kolpyaMR",
            password: "rst097481",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 11,
            subId: 4,
            login: "sbi57korsakMR",
            password: "rst951682",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 12,
            subId: 4,
            login: "sbi57krasnoMR",
            password: "rst541295",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 13,
            subId: 4,
            login: "sbi57kromsMR",
            password: "rst915865",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 14,
            subId: 4,
            login: "sbi57livenMR",
            password: "rst075829",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 15,
            subId: 4,
            login: "sbi57maloaMR",
            password: "rst658292",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 16,
            subId: 4,
            login: "sbi57mcensMR",
            password: "rst094904",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 17,
            subId: 4,
            login: "sbi57novodMR",
            password: "rst298741",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 18,
            subId: 4,
            login: "sbi57novosMR",
            password: "rst217400",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 19,
            subId: 4,
            login: "sbi57orlovMR",
            password: "rst274765",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 20,
            subId: 4,
            login: "sbi57pokrovMR",
            password: "rst428147",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 21,
            subId: 4,
            login: "sbi57sverdlMR",
            password: "rst642165",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 22,
            subId: 4,
            login: "sbi57soskoMR",
            password: "rst865421",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 23,
            subId: 4,
            login: "sbi57trosnMR",
            password: "rst776463",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 24,
            subId: 4,
            login: "sbi57urickMR",
            password: "rst879965",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 25,
            subId: 4,
            login: "sbi57hotynMR",
            password: "rst461596",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 26,
            subId: 4,
            login: "sbi57shablMR",
            password: "rst786494",
            isLogged: false,
            balance: 500,
            type: "referral",
          },





          {
            id: 0,
            subId: 5,
            login: "sbi71donskGO",
            password: "rst012740",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 1,
            subId: 5,
            login: "sbi71novomGO",
            password: "rst857563",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 2,
            subId: 5,
            login: "sbi71tulskGO",
            password: "rst021471",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 3,
            subId: 5,
            login: "sbi71novogGO",
            password: "rst024048",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 4,
            subId: 5,
            login: "sbi71slavnGO",
            password: "rst165713",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 5,
            subId: 5,
            login: "sbi71alexsMR",
            password: "rst921465",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 6,
            subId: 5,
            login: "sbi71arsenMR",
            password: "rst914085",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 7,
            subId: 5,
            login: "sbi71belevMR",
            password: "rst850949",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 8,
            subId: 5,
            login: "sbi71bogorMR",
            password: "rst094047",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 9,
            subId: 5,
            login: "sbi71venyoMR",
            password: "rst018416",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 10,
            subId: 5,
            login: "sbi71volovMR",
            password: "rst158195",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 11,
            subId: 5,
            login: "sbi71dubenMR",
            password: "rst914858",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 12,
            subId: 5,
            login: "sbi71efremMR",
            password: "rst715691",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 13,
            subId: 5,
            login: "sbi71zaoksMR",
            password: "rst857856",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 14,
            subId: 5,
            login: "sbi71kamenMR",
            password: "rst123648",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 15,
            subId: 5,
            login: "sbi71kimovMR",
            password: "rst958581",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 16,
            subId: 5,
            login: "sbi71kireevMR",
            password: "rst265895",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 17,
            subId: 5,
            login: "sbi71kurkiMR",
            password: "rst526568",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 18,
            subId: 5,
            login: "sbi71leninMR",
            password: "rst918470",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 19,
            subId: 5,
            login: "sbi71odoevMR",
            password: "rst195813",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 20,
            subId: 5,
            login: "sbi71plavsMR",
            password: "rst128475",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 21,
            subId: 5,
            login: "sbi71suvorMR",
            password: "rst170574",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 22,
            subId: 5,
            login: "sbi71teploMR",
            password: "rst821490",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 23,
            subId: 5,
            login: "sbi71uzolMR",
            password: "rst927572",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 24,
            subId: 5,
            login: "sbi71chernMR",
            password: "rst914984",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 25,
            subId: 5,
            login: "sbi71shekiMR",
            password: "rst851819",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 26,
            subId: 5,
            login: "sbi71yasnoMR",
            password: "rst751481",
            isLogged: false,
            balance: 500,
            type: "referral",
          },



          
          {
            id: 0,
            subId: 6,
            login: "sbi62kasimGO",
            password: "rst916964",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 1,
            subId: 6,
            login: "sbi62ryazaGO",
            password: "rst714844",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 2,
            subId: 6,
            login: "sbi62sasovGO",
            password: "rst984814",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 3,
            subId: 6,
            login: "sbi62skopiGO",
            password: "rst318940",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 4,
            subId: 6,
            login: "sbi62aleksMR",
            password: "rst008442",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 5,
            subId: 6,
            login: "sbi62ermisMR",
            password: "rst014104",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 6,
            subId: 6,
            login: "sbi62zaharMR",
            password: "rst014552",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 7,
            subId: 6,
            login: "sbi62kadomMR",
            password: "rst164194",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 8,
            subId: 6,
            login: "sbi62kasimMR",
            password: "rst814685",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 9,
            subId: 6,
            login: "sbi62klepkMR",
            password: "rst145719",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 10,
            subId: 6,
            login: "sbi62korabMR",
            password: "rst807013",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 11,
            subId: 6,
            login: "sbi62milosMR",
            password: "rst014149",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 12,
            subId: 6,
            login: "sbi62mihayMR",
            password: "rst436280",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 13,
            subId: 6,
            login: "sbi62pitelMR",
            password: "rst097026",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 14,
            subId: 6,
            login: "sbi62pronsMR",
            password: "rst546738",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 15,
            subId: 6,
            login: "sbi62putyaMR",
            password: "rst914818",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 16,
            subId: 6,
            login: "sbi62rybnoMR",
            password: "rst512814",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 17,
            subId: 6,
            login: "sbi62ryazhMR",
            password: "rst641296",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 18,
            subId: 6,
            login: "sbi62ryazaMR",
            password: "rst648313",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 19,
            subId: 6,
            login: "sbi62sapozMR",
            password: "rst048297",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 20,
            subId: 6,
            login: "sbi62saraeMR",
            password: "rst741984",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 21,
            subId: 6,
            login: "sbi62sasovMR",
            password: "rst048104",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 22,
            subId: 6,
            login: "sbi62skopiMR",
            password: "rst482491",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 23,
            subId: 6,
            login: "sbi62spassMR",
            password: "rst164916",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 24,
            subId: 6,
            login: "sbi62staroMR",
            password: "rst914764",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 25,
            subId: 6,
            login: "sbi62uholoMR",
            password: "rst714765",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 26,
            subId: 6,
            login: "sbi62chuchMR",
            password: "rst716491",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 27,
            subId: 6,
            login: "sbi62shatsMR",
            password: "rst085715",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
          {
            id: 28,
            subId: 6,
            login: "sbi62shiloMR",
            password: "rst049401",
            isLogged: false,
            balance: 500,
            type: "referral",
          },
        ])
      );
    } else if (
      JSON.parse(localStorage.getItem("secret") || "").find(
        (account: FormValuesType) => account.isLogged
      )
    ) {
      replace("/regions");
    }
  }, []);

  const initialValues: FormValuesType = {
    login: "",
    password: "",
  };

  const onSubmit = (values: FormValuesType) => {
    const accounts = JSON.parse(localStorage.getItem("secret") || "");
    const account = accounts.find(
      (account: FormValuesType) =>
        account.login === values.login && account.password === values.password
    );

    account.isLogged = true;

    localStorage.setItem("secret", JSON.stringify(accounts));

    if (account) {
      replace("/regions");
    }
  };

  return (
    <Box w="300px" backgroundColor="white" borderRadius="md" p="12px">
      <Formik initialValues={initialValues} onSubmit={onSubmit}>
        <Form>
          <VStack>
            <Text>Вход</Text>
            <Field
              id="login"
              name="login"
              placeholder="Логин"
              component={InputWithLabel}
            />
            <Field
              id="password"
              name="password"
              placeholder="Пароль"
              type="password"
              component={InputWithLabel}
            />
            <Button type="submit" colorScheme="blue">
              Войти
            </Button>
          </VStack>
        </Form>
      </Formik>
    </Box>
  );
};
